DOMAIN = "avrii"
PLATFORMS = ["sensor", "switch", "number"]

CONF_HOST = "host"

DEFAULT_PORT = 502
DEFAULT_SLAVE = 1

# ⚡ ULTRA REAL TIME
SCAN_INTERVAL = 0.5

INTEGRATION_SENSORS_FILE = "sensors.yaml"
INTEGRATION_SWITCHES_FILE = "switches.yaml"

# ---- ULTRA SETTINGS ----
MODBUS_TIMEOUT = 2
MODBUS_RETRIES = 0

WATCHDOG_INTERVAL = 15
WATCHDOG_MAX_NO_UPDATE = 20
AUTO_SOCKET_RESET_HOURS = 4
ERROR_BACKOFF_THRESHOLD = 3